import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { ClientSessionProvider } from "@/providers/session-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientSessionProvider>
        <body
          className={"antialiased bg-black"}
          suppressHydrationWarning
        >
          {children}
        </body>
      </ClientSessionProvider>
    </html>
  );
}
